---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
library(plyr)
unzip("activity.zip")
activity=read.csv('activity.csv')
activity$date=as.Date(activity$date)
activ2=subset(activity,!is.na(activity$steps))

act2=ddply(activ2, .(date),summarize, steps.per.day=sum(steps))
## What is mean total number of steps taken per day?
act2=ddply(activ2, .(date),summarize, steps.per.day=sum(steps))
# What is mean total number of steps taken per day?
# For this part of the assignment, you can ignore the missing values in the dataset.
# 1. Calculate the total number of steps taken per day
act2=ddply(activ2, .(date),summarize, steps.per.day=sum(steps))
act2
# 2. If you do not understand the difference between a histogram and a barplot, research the difference between them. Make a histogram of the total number of steps taken each day

hist(act2$steps.per.day, col = 'orange',xlab='Steps per Day', main='Distribution of frequencies - Total steps per day')

# 3. Calculate and report the mean and median of the total number of steps taken per day
mean(act2$steps.per.day)
median(act2$steps.per.day)



## What is the average daily activity pattern?
# 1. Make a time series plot (i.e. type="l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

act3=ddply(activ2, .(interval),summarize, avg.steps.interval=sum(steps))

plot(act3$avg.steps.interval~act3$interval, type='l', xlab='Interval(5 min)',ylab='Avg. Steps per Interval', col = '#04B45F', lwd=2, bty="n")
xx <- c(act3$interval, rev(act3$interval))
yy <- c(rep(0, nrow(act3)), rev(act3$avg.steps.interval))
polygon(xx, yy, col='#04B45F')
#2. Which 5-minute interval ,on average across all the days in the dataset, contains the maximum number of steps?
act3$interval[which.max(act3$avg.steps.interval)]


## Imputing missing values

# Note that there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.

# Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
actNA=ddply(activity, .(date),summarize, NA.steps=sum(is.na(steps)))
actNA=subset(actNA,NA.steps !=0)
sum(actNA$NA.steps)
# Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
View(actNA2)
View(actNA2)
# Análise dos dois data frames permite ver que os NA values estão concentrados em alguns dias.
actNA2=ddply(activity, .(interval),summarize, NA.steps=sum(is.na(steps)))

# Create a new dataset that is equal to the original dataset but with the missing data filled in.
activity2=activity
# loop
for(i in 1:17568){
  interv=activity2[i,3]
  # If steps value in activity2 is NA...
  if(is.na(activity2[i,1])){
    # Replace NA Value for the mean of the interval
    activity2[i,1]=mean(activity2[activity2$interval==interv,]$steps,na.rm = TRUE)
  }
}
# Make a histogram of the total number of steps taken each day
act2NAf=ddply(activity2, .(date),summarize, steps.per.day=sum(steps))
hist(act2NAf$steps, col = '#01DFD7',xlab='Steps per Day', main='Distribution of frequencies - Total steps per day (NA values replaced)')
# and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?
mean(act2$steps.per.day)
median(act2$steps.per.day)
# histograma aumentou a frequência dos valores, mas o padrão de distribuição das frequências se manteve
# diferença nos valores iniciais - media e mediana ficaram iguais no dataset sem NA.  A média ficou igual no dataset 1 e 2;

act2NAf


## Are there differences in activity patterns between weekdays and weekends?
activity2$weekdays=weekdays(activity2$date)

activ2sem=subset(activity2, activity2$weekdays=="Segunda Feira" | activity2$weekdays=="Terça Feira" | activity2$weekdays=="Quarta Feira" | activity2$weekdays=="Quinta Feira" | activity2$weekdays=="Sexta Feira")

act2ds=ddply(activ2sem, .(interval),summarize, avg.steps.day=mean(steps))

activ2fds=subset(activity2, activity2$weekdays=="Sábado" | activity2$weekdays=="Domingo" )

act2fds=ddply(activ2fds, .(interval),summarize, avg.steps.day=mean(steps))
#panelplot:
par(mfrow=c(1,2))
#plot 1 - fds
plot(act2fds$avg.steps.day~act2fds$interval, type='l', xlab='Interval(5 min)',ylab='Avg. Steps per Interval', col = 'yellow', lwd=2, bty="n", main='Weekend')
xx2 <- c(act2fds$interval, rev(act2fds$interval))
yy2 <- c(rep(0, nrow(act2fds)), rev(act2fds$avg.steps.day))
polygon(xx2, yy2, col='yellow')
# plot2
plot(act2ds$avg.steps.day~act2ds$interval, type='l', xlab='Interval(5 min)',ylab='Avg. Steps per Interval', col = 'grey', lwd=2, bty="n", main='Weekday')
xx3 <- c(act2fds$interval, rev(act2fds$interval))
yy3 <- c(rep(0, nrow(act2ds)), rev(act2ds$avg.steps.day))
polygon(xx3, yy3, col='grey')

